// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Lexing         = require("bs-platform/lib/js/lexing.js");
var Lexer$Languid  = require("./lexer.bs.js");
var Parser$Languid = require("./parser.bs.js");

var lexbuf = Lexing.from_string("walk");

var command = Parser$Languid.prog(Lexer$Languid.read, lexbuf);

if (!command.tag) {
  if (!command[0]) {
    console.log("walk");
  }
  
}

exports.lexbuf  = lexbuf;
exports.command = command;
/* lexbuf Not a pure module */
