// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest            = require("bs-jest/src/jest.js");
var Read$Slangwidge = require("../src/read.bs.js");

describe("read", (function () {
        Jest.test("it throws a parser error", (function () {
                var result = Read$Slangwidge.read("fuck you");
                var failure;
                if (result.tag) {
                  console.log(result[0]);
                  failure = /* true */1;
                } else {
                  failure = /* false */0;
                }
                return Jest.Expect[/* toBe */2](/* true */1, Jest.Expect[/* expect */0](failure));
              }));
        return Jest.test("it throws a syntax error", (function () {
                      var result = Read$Slangwidge.read("^#! $$");
                      var failure;
                      if (result.tag) {
                        console.log(result[0]);
                        failure = /* true */1;
                      } else {
                        failure = /* false */0;
                      }
                      return Jest.Expect[/* toBe */2](/* true */1, Jest.Expect[/* expect */0](failure));
                    }));
      }));

/*  Not a pure module */
